// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctvigehkgxetjxupayhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0dmlnZWhrZ3hldGp4dXBheWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0NzE1ODQsImV4cCI6MjA1MDA0NzU4NH0.T5UEuZX5Xq9yI7QW2DU4Ouoez6_-sw3gkcDY77dNvyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);